name: salah_prayer_time
description: "Simple and modern Salah prayer time app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  geocoding: ^2.2.0
  hijri: ^3.0.0
  table_calendar: ^3.1.2



    # ðŸŒ Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # ðŸ”” Notifications
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

  # ðŸŒ Network & storage
  http: ^1.1.0
  shared_preferences: ^2.2.0

  # ðŸ“ Location & Maps
  geolocator: ^9.0.2
  google_maps_flutter: ^2.4.0
  flutter_polyline_points: ^3.1.0

  # ðŸŽ iOS icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ðŸŽ¨ App icons & splash
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true

  assets:
    - assets/

# ðŸŽ¯ App launcher icons
flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png

# ðŸ’¦ Splash screen
flutter_native_splash:
  color: "#2EC4B6"
  image: assets/splash_logo.png
  android: true
  ios: true
