name: salah_prayer_time
description: "Simple and modern Salah prayer time app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

  http: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.0

  geolocator: ^9.0.2

  google_maps_flutter: ^2.4.0
  flutter_polyline_points: ^3.1.0

  cupertino_icons: ^1.0.8

#  flutter_native_splash: ^2.2.16
#  flutter_native_splash:
#  color: "#2EC4B6"
#  image: assets/splash_logo.png
#  android: true
#  ios: true



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#2EC4B6"
  image: assets/splash_logo.png
  android: true
  ios: true
